### ISSUE TITLE
Tests are failing.

### ISSUE THREAD

**Issue by tisto** [plone/plone.app.workflowmanager#56]
```
bin/test
Running plone.app.workflowmanager.testing.FUNCTIONAL_MANAGER_TESTING tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.160 seconds.
  Set up plone.app.testing.layers.PloneFixtureCould not install product Products.SecureMailHost
 in 7.561 seconds.
  Set up plone.app.workflowmanager.testing.ManagerFixture in 0.202 seconds.
  Set up plone.app.workflowmanager.testing.FUNCTIONAL_MANAGER_TESTING in 0.000 seconds.
  Running:
    1/1 (100.0%)
Failure in test /home/travis/build/plone/plone.app.workflowmanager/src/plone/app/workflowmanager/tests/../browser.txt
Traceback (most recent call last):
  File "/opt/python/2.7.13/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/opt/python/2.7.13/lib/python2.7/doctest.py", line 2226, in runTest
    raise self.failureException(self.format_failure(new.getvalue()))
AssertionError: Failed doctest test for browser.txt
  File "/home/travis/build/plone/plone.app.workflowmanager/src/plone/app/workflowmanager/tests/../browser.txt", line 0
----------------------------------------------------------------------
File "/home/travis/build/plone/plone.app.workflowmanager/src/plone/app/workflowmanager/tests/../browser.txt", line 36, in browser.txt
Failed example:
    'one_state_workflow' in browser.contents
Expected:
    False
Got:
    True
  Ran 1 tests with 1 failures and 0 errors in 6.747 seconds.
Running plone.app.workflowmanager.testing.INTEGRATION_MANAGER_TESTING tests:
  Tear down plone.app.workflowmanager.testing.FUNCTIONAL_MANAGER_TESTING in 0.000 seconds.
  Set up plone.app.workflowmanager.testing.INTEGRATION_MANAGER_TESTING in 0.000 seconds.
  Running:
                  
  Ran 21 tests with 0 failures and 0 errors in 0.408 seconds.
Tearing down left over layers:
  Tear down plone.app.workflowmanager.testing.INTEGRATION_MANAGER_TESTING in 0.000 seconds.
  Tear down plone.app.workflowmanager.testing.ManagerFixture in 0.003 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.043 seconds.
  Tear down plone.testing.z2.Startup in 0.005 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.003 seconds.
Total: 22 tests, 1 failures, 0 errors in 15.750 seconds.
```

**Comment by tisto** [comment]
One failing test for Plone 4.3. Multiple failures in Plone 5.0/5.1.

**Comment by tisto** [comment]
All tests in master branch pass now.
